server:
  launch: true
  port: 3001
  tools_path: tools.jsonl
  wrap: none
model:
  provider: ollama
  name: qwen2.5:7b-instruct
  temperature: 0.2
retrieval:
  k: 6
  ic_penalty_mu: 0.6
  redundancy_penalty_nu: 0.3
complexity:
  slot_threshold: 0.65
  gate_threshold: 0.05
limits:
  max_steps: 6
  max_retries: 2
tasks:
  path: tests/fuzzy_tasks.jsonl
logging:
  out_dir: runs/local_qwen
tools_path: tools.jsonl
